### ISSUE TITLE
Live Editor won't let me edit Kits colour

### ISSUE THREAD

**Issue by andreaBromano** [xAranaktu/FC-25-Live-Editor#19] opened 2024-12-18 11:35 UTC
![Untitled](https://github.com/user-attachments/assets/8b4a080f-8ea5-411a-b233-e3bb9e00f4d8)
![Untitledaaa](https://github.com/user-attachments/assets/ac465d15-a57f-457e-b058-907cd4f621c8)

When I try to edit font colour, the tab with "Serie B" shows the 3rd kit but it seems that any changes made in this tab doesn't effect the game.
If I try to edit the "Team Kits" tab it does modify the colours od the fonts but 3rd kit doesn't appears.

**Comment by xAranaktu** [comment] 2024-12-21 18:04
In FC 25 the "teamkits" table is no longer part of the career file and because of that, it's also not possible to save changes permanently in that table. As it's not a bug in LE it won't be fixed.

**Closed by xAranaktu** 2024-12-21 18:04 UTC
